### ISSUE TITLE
Linux Python Error

### ISSUE THREAD

**Issue by casey-ac** [Neotod/Todd_and_his_friends#1]
When trying to run the game on Debian with Python 3.8.2 and Pygame 1.9.6 the result is the following error: 
>fienix@Fienix:~/Downloads/Todd_and_his_friends-master$ python3 Todd_and_his_friends.py
>pygame 1.9.6
>Hello from the pygame community. https://www.pygame.org/contribute.html
>Traceback (most recent call last):
>  File "Todd_and_his_friends.py", line 20, in <module>
>    game = Game()
>  File "/home/fienix/Downloads/Todd_and_his_friends-master/data/sources/game.py", line 46, in __init__
>    self.healer = Healer()
>  File "/home/fienix/Downloads/Todd_and_his_friends-master/data/sources/npc.py", line 17, in __init__
>    self.surface = self.gif.render_surface()
>  File "/home/fienix/Downloads/Todd_and_his_friends-master/data/sources/pygameGIF.py", line 33, in render_surface
>    image = pygame.image.load(image_path)
>pygame.error: Couldn't open ./data/images/npc/healer/idle\1.png

**Comment by elliot19soltani** [comment]
Hi, casey-ac,
Thank you for issuing this bug, now this minor bug was fixed and you can play the game again :).
